name: Generate site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-site:
    name: Generate Site
    runs-on: ubuntu-20.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: Install node packages
        run: npm install

      - name: Generate site
        run: npm run site-build

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # NOTE: 変更履歴が必要な場合は false に変更
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
